import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import Copyright from '@/app/components/Copyright/Copyright'
import HeaderWarp from '@/app/components/Header/HeaderWarp'
import Header from '@/app/components/Header/Header'
import HomeBanner from '@/app/components/HomeBanner/HomeBanner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderWarp
          header={<Header />}
          homeBanner={<HomeBanner />}
        ></HeaderWarp>
        {children}
        <Copyright></Copyright>
      </body>
    </html>
  )
}
