import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/components/Header/Header'
import { clsx } from 'clsx'
import { basePath } from '@/lib/util'
import React from 'react'
import Main from '@/app/components/Main/Main'
import Copyright from '@/app/components/Copyright/Copyright'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Main>{children}</Main>
        <Copyright></Copyright>
      </body>
    </html>
  )
}
